# Change these first
owner: hideki0403 # Your GitHub organization or username, where this repository lives
repo: status.yukineko.me # The name of this repository

sites:
  - name: Blog (ゆきねこの備忘録)
    url: https://yukineko.me
  - name: Misskey (隠れ家)
    url: https://misskey.yukineko.me
  - name: GitServer (Gitea)
    url: https://git.yukineko.me

status-website:
  cname: status.yukineko.me
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Statuses
  introTitle: "サービス稼働状況"
  introMessage: 現在のサービス稼働状況です
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
