# Change these first
owner: hideki0403 # Your GitHub organization or username, where this repository lives
repo: status.yukineko.me # The name of this repository

sites:
  - name: [Web] Blog (ゆきねこの備忘録)
    url: https://yukineko.me
  - name: [Web] Misskey (隠れ家)
    url: https://misskey.yukineko.me
  - name: [Web] GitServer (Gitea)
    url: https://git.yukineko.me
  - name: [Bot] EarthquakeEarlyWarningPlus
    url: https://discord-status-api.glitch.me/api/v1/status/460323119651880960?token=${{secrets.API_TOKEN}}

status-website:
  cname: status.yukineko.me
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Statuses
  introTitle: "サービス稼働状況"
  introMessage: 現在のサービス稼働状況です
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
